### ISSUE TITLE
python

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/py-solc#37]
* `py-solc` Version: 1.4.0
* `solc` Version: 0.4.11
* Python Version: 3.5
* OS: osx

### What was wrong?

Running `python -m solc.install v0.4.11`

... does not complete:

```
==> Caveats
To have launchd start ethereum/ethereum/ethereum now and restart at login:
  brew services start ethereum/ethereum/ethereum
==> Summary
🍺  /usr/local/Cellar/ethereum/1.7.2: 10 files, 51.2MB, built in 1 minute 32 seconds
==> Upgrading paritytech/paritytech/parity --stable
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.7.9/x86_64-apple-darwin/parity
Already downloaded: /Users/mikkoohtamaa/Library/Caches/Homebrew/parity-1.7.9
Error: Empty installation
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mikkoohtamaa/code/tm/trading/venv/lib/python3.5/site-packages/solc/install.py", line 483, in <module>
    install_solc(identifier)
  File "/Users/mikkoohtamaa/code/tm/trading/venv/lib/python3.5/site-packages/solc/install.py", line 473, in install_solc
    install_fn()
  File "/Users/mikkoohtamaa/code/tm/trading/venv/lib/python3.5/site-packages/solc/install.py", line 406, in install_from_source
    install_solc_dependencies(identifier)
  File "/Users/mikkoohtamaa/code/tm/trading/venv/lib/python3.5/site-packages/solc/install.py", line 301, in install_solc_dependencies
    install_deps_script_path,
  File "/Users/mikkoohtamaa/code/tm/trading/venv/lib/python3.5/site-packages/solc/install.py", line 98, in check_subprocess_call
    **proc_kwargs
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', '/Users/mikkoohtamaa/.py-solc/solc-v0.4.11/source/scripts/install_deps.sh']' returned non-zero exit status 1
make: *** [install-solc-0-4-11] Error 1
```

Not sure what `Empty installation` means.

#### Cute Animal Picture

```
 
   ______________
   |  D.A.B.'S  |            (__)          (__)          (__)          (__)
   |    USED    |            (uu)          (uu)          (uu)          (uu)
   |    COWS    |     /-------\/    /-------\/    /-------\/    /-------\/
   |____________|   / |     ||    / |     ||    / |     ||    / |     ||
         ||        *  ||----||   *  ||----||   *  ||----||   *  ||----||
         ||           ~~    ~~      ~~    ~~      ~~    ~~      ~~    ~~
   ______||_______
   | EASY CREDIT |           (__)          (__)          (__)          (__)
   |_____________|           (uu)          (uu)          (uu)          (uu)
         ||           /-------\/    /-------\/    /-------\/    /-------\/
         ||          / |     ||    / |     ||    / |     ||    / |     ||
         ||         *  ||----||   *  ||----||   *  ||----||   *  ||----||
         ||            ~~    ~~      ~~    ~~      ~~    ~~      ~~    ~~
```

**Comment by miohtama** [comment]
Related https://github.com/paritytech/parity/issues/6923

**Comment by pipermerriam** [comment]
@miohtama awkward.  I think this is only related because you have `parity` installed and part of the install scripts for the solc compiler involves running a `brew upgrade`.
